config/routes.rb
Edcal::Application.routes.draw do

  match '/', :controller => :home, :action => :index

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete '/users/disconnect/:provider', 
      :to => 'users#disconnect_omniauth_provider', 
      :as => 'disconnect_omniauth_provider'
  end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def self.find_for_facebook_oauth(access_token, signed_in_resource = nil)
    data = access_token.extra.raw_info
    User.where(:facebook_id => data.id).first
  end

  def self.find_for_twitter_oauth(access_token, signed_in_resource = nil)
    data = access_token
    User.where(:twitter_id => data.uid).first
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.facebook_id = data["id"]
      elsif data = session["devise.twitter_data"]
        user.twitter_id = data["uid"]
      end
      # TODO: add other providers
    end
  end

  def connect_with provider, authdata
    case provider
    when :twitter
      self.twitter_id = authdata['uid']
    when :facebook
      self.facebook_id = authdata['uid']
    end
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# copied from: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorize :facebook do
      session["devise.facebook_data"] = request.env["omniauth.auth"]
    end
  end

  def twitter
    authorize :twitter do
      # http://stackoverflow.com/questions/7117200/devise-for-twitter-cookie-overflow-error
      session["devise.twitter_data"] = request.env["omniauth.auth"].except('extra')
    end
  end

  private
  def authorize provider
    @user = User.send "find_for_#{provider}_oauth", request.env["omniauth.auth"], current_user
    
    provider_name = provider.to_s.titleize

    # if current_user exists:
    # if @user is nil, connecting the account
    # if @user is not nil and not equal to current_user, show an error
    # else, see below:
    if current_user
      if @user.nil?
        current_user.connect_with provider, request.env['omniauth.auth']

        flash[:success] = "Your account has been connected to #{provider_name}."
      elsif @user != current_user
        # TODO: I18n
        flash[:error] = "That #{provider_name} account is already linked to a different user."
      else
        flash[:notice] = "Your account is already linked with the #{provider_name} account." 
      end
      redirect_to edit_user_registration_path
    else
      if @user
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => provider.to_s.titleize
        sign_in_and_redirect @user, :event => :authentication
      else
        yield if block_given?
        redirect_to new_user_registration_url
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!

  def disconnect_omniauth_provider
    provider = params[:provider]
    if Devise.omniauth_providers.include? provider.to_sym
      current_user.update_attribute("#{provider}_id", nil)
      current_user.save

      flash[:success] = "Your account has been disconnected from #{provider.titleize}."
    end
    redirect_to edit_user_registration_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Hello!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Rails.configuration.application_name
    
    = stylesheet_link_tag    "application"
    = yield(:css_includes)

    = javascript_include_tag "application"
    = yield(:js_includes)
    
    = csrf_meta_tags
  %body
    = render :partial => 'shared/header'
    #content-container.container
      - [:success, :error, :message].each do |msg|
        - if flash[msg]
          %div{:class => "alert-message #{msg.to_s}"}= flash[msg]

      = yield

app/views/shared/_header.html.haml
.topbar
  .fill
    .container
      %a.brand= Rails.configuration.application_name
      - if user_signed_in?
        %ul.nav
          %li= link_to 'Something', '#'
        .pull-right
          %ul.nav
            %li= link_to current_user.email, edit_user_registration_path
            %li= link_to 'Sign out', destroy_user_session_path, :method => :delete
      - else
        .pull-right
          %ul.nav
            %li=link_to 'Sign in',
                new_user_session_path
            %li=link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
            %li=link_to 'Sign up',new_registration_path(:user)

app/views/shared/forms/_text_field.html.haml
.clearfix{:class => "#{'error' unless obj.errors[field].empty?}"}
  %label= label
  .input
    =f.text_field field
    %span.help-block= obj.errors[field].join(', ')